apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: orders-service
  namespace: default
  labels:
    app: orders-service
    example: orders-service
spec:
  host: orders-service.bc-api-gateway.goatz.shoot.canary.k8s-hana.ondemand.com
  gateway: kyma-system/kyma-gateway
  service:
    name: httpbin
    port: 8000
  rules:
    - path: /orders
      service:
          name: orders-service
          port: 80
      methods: ["GET","POST"]
      accessStrategies:
        - handler: allow
    - path: /hello
      service:
          name: helloworld
          port: 5000
      methods: ["GET","POST"]
      accessStrategies:
        - handler: allow
    - path: /.*
      methods: ["GET","POST"]
      accessStrategies:
        - handler: noop
