apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: multiple-service
  namespace: default
  labels:
    app: multiple-service
    example: multiple-service
spec:
  host: 3svc.bc-api-gateway.goatz.shoot.canary.k8s-hana.ondemand.com
  gateway: kyma-system/kyma-gateway
  service:
    name: httpbin
    port: 8000
  rules:
    - path: /orders
      service:
          name: orders-service
          port: 80
      methods: ["GET"]
      accessStrategies:
        - handler: oauth2_introspection
          config:
            required_scope: ["read"]
    - path: /hello
      service:
          name: helloworld
          port: 5000
      methods: ["GET","POST"]
      accessStrategies:
        - handler: noop
    - path: /headers|/ip
      methods: ["GET","POST"]
      accessStrategies:
        - handler: noop
      mutators: [
          {
            "handler": "header",
            "config": {
              "headers": {
                "X-User": "test",
                "X-Some-Arbitrary-Data": "test"
              }
            }
          }
        ]
