apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: orders-service-svc-with-override
  namespace: default
  labels:
    app: orders-service
    example: orders-service
spec:
  host: testHost.com
  service:
    name: orders-service
    port: 80
  gateway: kyma-system/kyma-gateway
  rules:
    - path: /.*
      service:
        name: orders-service
        port: 8008
      methods: ["GET", "POST"]
      accessStrategies:
        - handler: noop
      mutators: []
